apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app: mydeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydeploy  # This should match the label in the Pod template
  template:
    metadata:
      labels:
        app: mydeploy  # Match the label with the selector in the Service
    spec:
      containers:
      - name: proj2-container  # Give a name to the container
        image: tejashree14/proj2  # Ensure the image exists
        ports:
        - containerPort: 80  # Exposed container port

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: mydeploy  # Match the label from the Deployment
  ports:
    - port: 80         # Port the service listens on
      targetPort: 80   # Port on the container
      nodePort: 30008  # Custom NodePort (within the range 30000-32767)
